name: payment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_credit_card: ^4.0.1
  flutter_stripe: ^10.0.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
